name: taxi_callkit_bridge
description: Taxi native CallKit bridge.
version: 0.0.9

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_callkit_incoming:
    git:
      url: https://github.com/MohamedAzazy2022/taxi_flutter_callkit_incoming.git
      ref: v2.5.8-taxi.4

  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.taxi_callkit_bridge
        pluginClass: TaxiCallkitBridgePlugin
      ios:
        pluginClass: TaxiCallkitBridgePlugin